### ISSUE TITLE
Discrepancies to `drun`

### ISSUE THREAD

**Issue by ggreif** [dfinity/interface-spec#10]
So far I have found a few aspects where `drun` differs from `ic-ref`:
- former rejects hyphenated endpoints (e.g. `memory-footprint`)
- former rejects IC custom sections (i.e. prefixed with `icp:`) that are > 64kB

I am asking the oracle here, to clarify what the expected behaviour is, and shall write follow-ups.

**Comment by nomeata** [comment]
With endpoints you mean canister method names? The spec has no restrictions, as long as its UTF8-encoded text, and even stuff like the empty string should work. I had always meant to test hat with `ic-ref-test`, but never got around to do it; I think there is an issue on `dfinity/ic-ref` about it.

I also don’t see a reason for restricting the size of custom sections.

**Comment by ggreif** [comment]
Yes, endpoint = method name. Thanks for the explanation!

**Comment by mraszyk** [comment]
Methods with names such as `canister_query get-counter-#` are allowed by the latest replica.

**Comment by mraszyk** [comment]
The limit on custom section name length (incl. `icp:public ` or `icp:private ` prefix) is 100000 as of now (see [here](https://github.com/bytecodealliance/wasm-tools/blob/1f5170f8e4bda1080ef3292ae74a4f4bec7112b9/crates/wasmparser/src/limits.rs#L26)).

**Comment by mraszyk** [comment]
More generally, there are wasmtime-specific [limits](https://github.com/bytecodealliance/wasm-tools/blob/1f5170f8e4bda1080ef3292ae74a4f4bec7112b9/crates/wasmparser/src/limits.rs) that are not reflected in the spec.

**Comment by mraszyk** [comment]
`ic-ref` has been deprecated and thus I'm closing this issue.
