### ISSUE TITLE
Rejecting management canister calls

### ISSUE THREAD

**Issue by mraszyk** [dfinity/interface-spec#171]
A state transition for rejecting management canister calls is missing.

**Comment by timohanke** [comment]
Interested in what this refers to. Could you elaborate a little bit?

**Comment by mraszyk** [comment]
The state transitions [part](https://ic-interface-spec.netlify.app/#_state_transitions) of the spec provides transitions modelling successful management canister calls, e.g., canister creation [call](https://ic-interface-spec.netlify.app/#_ic_management_canister_canister_creation), but there's no transition to produce a reject message if the management canister call is invalid.

**Comment by mraszyk** [comment]
Fixed by https://github.com/dfinity/interface-spec/pull/295
