### ISSUE TITLE
Clarify memory allocation

### ISSUE THREAD

**Issue by timohanke** [dfinity/interface-spec#289]
https://github.com/dfinity/interface-spec/blob/6e57f8ab8c58f6834cf60dd3e6182fac31931b17/spec/index.md?plain=1#L1959

The description starts by describing memory_allocation as an upper bound ("Any attempt to grow memory usage beyond this allocation will fail.").

The next sentence ("If the IC cannot provide the requested allocation") implies that it is also a lower bound. That is confusing because it is not clear to the reader before this sentence that it is both an upper and lower bound.

Could someone improve this text please?

**Comment by mraszyk** [comment]
> That is confusing because it is not clear to the reader before this sentence that it is both an upper and lower bound.

> Could someone improve this text please?

Do you have a concrete suggestion in mind?

**Comment by timohanke** [comment]
I don't know if it is correct. My understanding is something like this:

Must be a number between 0 and 2<sup>48</sup> (i.e 256TB), inclusively.
It indicates the maximum amount of memory that the canister is allowed to use in total _and_ also guarantees availability of this amount of memory.
If the IC cannot guarantee the requested allocation, for example because it is oversubscribed, then the call will be rejected. Afterwards, any attempt to grow memory usage beyond this allocation will fail.
If set to 0, then memory growth of the canister will have no limit but will only be best-effort and subject to the available memory on the IC.
