### ISSUE TITLE
Using canister_id type instead of principal

### ISSUE THREAD

**Issue by sudoshreyansh** [dfinity/interface-spec#309]
https://github.com/dfinity/interface-spec/blob/78c12c2ccc6477ec6fe98d8b3f9bd590540b830c/spec/_attachments/ic.did#L176

The type being used here is `principal` but the spec already defines a type `canister_id`. It seems more appropriate to use the latter here.

**Comment by mraszyk** [comment]
In candid, there's no dedicated type for a canister ID which is why we use the type synonym.
