### ISSUE TITLE
Undefined field in `Code installation/upgrade` transitions

### ISSUE THREAD

**Issue by ulan** [dfinity/interface-spec#80]
`IC Management Canister: Code installation` and `IC Management Canister: Code upgrade` refer to `M.receiver`, but `M` doesn't have that field because `M` is `CallMessage` not `FuncMessage`.

I think the fix would be to replace `M.receiver` with `A.canister_id`

Links to the transitions:
- https://ic-interface-spec.netlify.app/#_ic_management_canister_code_installation
- https://ic-interface-spec.netlify.app/#ic_management_canister_code_upgrade

**Comment by nomeata** [comment]
BTW, the above URL is often behind. You can link to the master version here

https://ic-interface-spec.netlify.app/#_ic_management_canister_code_installation

(At least I believe the netlify deploy is still up to date.)

**Comment by ulan** [comment]
This will be fixed by https://github.com/dfinity/interface-spec/pull/77

**Comment by mraszyk** [comment]
I'm closing this issue as it has been fixed in #77.
